name: release
on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  MDBOOK_VERSION: 0.4.51
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4

      - name: Get the version
        id: get_version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: list artifacts
        run: |
          echo "Artifacts:"
          ls -lR
      - name: Install packages
        run: sudo apt update && sudo apt install -y upx-ucl zip

      - name: Rename binaries
        run: |
          cd ~/work/mdbook-lang/mdbook-lang
          mv x86_64-unknown-linux-gnu mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-unknown-linux-gnu
          mv x86_64-apple-darwin mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-apple-darwin
          # mv x86_64-pc-windows-msvc mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-pc-windows-msvc

      - name: Compress binaries
        run: |
          chmod u+x mdbook-lang-*/mdbook-lang*
          upx --best mdbook-lang-*/mdbook-lang*
          zip -r mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-unknown-linux-gnu{.zip,}
          zip -r mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-apple-darwin{.zip,}
          # zip -r mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-pc-windows-msvc{.zip,}

     

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ env.RELEASE_VERSION }}
          files: |
            mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-unknown-linux-gnu.zip
            mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-apple-darwin.zip
            # mdbook-lang-${{ env.RELEASE_VERSION }}-x86_64-pc-windows-msvc.zip
